pis:
  - hostname: "pi1.local"
    lens: "human_time"
    physical_location: ""
  - hostname: "pi2.local"
    lens: "infrastructure_time"
    physical_location: ""
  - hostname: "pi3.local"
    lens: "environmental_time"
    physical_location: ""
  - hostname: "pi4.local"
    lens: "digital_time"
    physical_location: ""
  - hostname: "pi5.local"
    lens: "liminal_time"
    physical_location: ""
  - hostname: "pi6.local"
    lens: "more_than_human_time"
    physical_location: ""
